# docker-compose.yml
version: '3'
services:
  app1:
    build: .
    environment:
      - APP_ID=instance1
    ports:
      - "9091:8080"

  app2:
    build: .
    environment:
      - APP_ID=instance2
    ports:
      - "9092:8080"

  app3:
    build: .
    environment:
      - APP_ID=instance3
    ports:
      - "9093:8080"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
      - app3


